## Penser à changers les informations indiquées avec les chevrons (les TODO vous indiquerons où)
services:
  # TODO
  requiem_front:
    build : 
      context : ./requiem-for-a-spring-front
      
    # Ci-dessous la redirection du port à décommenter pour les tests en local
    # ports:
    #   - "8080:8080"

    # links permet d'indiquer que les conteneurs peuvent communiquer sur un réseau interne au moteur Docker
    # ici, le conteneur du "front" doit pouvoir échanger avec le conteneur du "back"
    links:
      # TODO
      - requiem_api

  # TODO
  requiem_api:
    build : 
      context : ./requiem-for-a-spring-api

    # Ci-dessous la redirection du port à décommenter pour les tests en local
    ports:
      - "8000:8000"

    # "depends_on" permet d'indiquer que le conteneur api doit attendre le lancement du conteneur "PostgreSQL" avant de démarrer
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      # TODO
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/requiem
      # TODO
      - SPRING_DATASOURCE_USERNAME=postgres
      # TODO
      - SPRING_DATASOURCE_PASSWORD=B@nLgU4qz*9?D~3n83
      # TODO : DDL auto ou pas ?
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres:15
    # TODO
    container_name: postgresdb
    environment:
      # TODO
      - POSTGRES_USER=postgres
      # TODO
      - POSTGRES_PASSWORD=B@nLgU4qz*9?D~3n83
      # TODO
      - POSTGRES_DB=requiem
    logging: # option de paramétrage des logs
      options:
        max-size: 10m # fichier de 10 Mo maximum
        max-file: "3" # jusqu'à 3 fichiers de log
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    # on ne redirige pas le port 5432 par sécurité, la base de données est ainsi inaccessible ailleurs que entre les conteneurs
    # Décommenter ces lignes pour pouvoir rediriger et ainsi pouvoir facilement tester en local
    # ports:
    #   - '5432:5432'
    volumes:
      # TODO ajout des volumes pour création automatique de la base de données à la création du conteneur
      # Attention, un dossier "db" doit être créé et contenir les scripts de création
      - ./requiem-for-a-spring-api/DB/dump/ScriptInitialisation.sql:/docker-entrypoint-initdb.d/ScriptInitialisation.sql:ro

  # Le service suivant correspond au "reverse proxy"
  # -> le serveur HTTP de type "nginx" agit comme un reverse proxy
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
      - "443:443" # exposition du port 443 (sécurisé)
    volumes:
      # ajout du fichier de configuration du nginx pour en faire un "reverse proxy"
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # ajout du chemin vers les certificats
      - ./nginx:/etc/nginx/conf.d/ 
    depends_on:
      - requiem_front
      - requiem_api